import { Field } from 'shared/components/Resource/List';
export const filterFields: Field[] = [
  {
    type: 'SearchInput',
    label: 'Search Properties',
    source:
      'parcel_number,location_address,notes,residential_ownership_type,residential_style,commercial_property_type,commercial_property_subtype',
    alwaysOn: true,
    fullWidth: true,
    resettable: true,
  },
  {
    type: 'ReferenceInput',
    label: 'Property Type',
    source: 'property_type_id',
    reference: 'property_types',
    allowEmpty: false,
    fullWidth: true,
    perPage: 2,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Type',
    source: 'commercial_property_type_id',
    reference: 'commercial_property_type',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Subtype',
    source: 'commercial_property_subtype_id',
    reference: 'commercial_property_subtype',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ subtype: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'subtype',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Ownership Type',
    source: 'residential_ownership_type_id',
    reference: 'residential_ownership_types',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Style',
    source: 'residential_style_id',
    reference: 'residential_styles',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ style: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'style',
      },
    ],
  },
];

export const exportFields = [
  'id',
  'property_type',
  'commercial_property_type',
  'commercial_property_subtype',
  'residential_ownership_type',
  'residential_style',
  'location_address',
  'subdivision',
  'parcel_number',
  'universal_property_identifier',
  'legal_description',
  'tax_id',
  'zoning',
  'total_acres',
  'year_built',
  'year_renovated',
  'site',
  'heating_cooling',
  'energy_efficient_items',
  'commercial_building_name',
  'commercial_buildings',
  'commercial_floors',
  'commercial_units',
  'commercial_gross_area',
  'residential_above_grade_bedrooms',
  'residential_above_grade_bathrooms',
  'residential_below_grade_bedrooms',
  'residential_below_grade_bathrooms',
  'residential_gross_living_area',
  'residential_basement_and_finished',
  'residential_functional_utility',
  'residential_garage_carport',
  'residential_porch_patio_deck',
  'residential_fireplaces',
  'residential_other',
  'notes',
  'created_at',
  'updated_at',
  'appraisals_count',
  'lease_comps_count',
  'sales_comps_count',
];
