import { Field } from 'shared/components/Resource/List';

export const filterFields: Field[] = [
  {
    type: 'SearchInput',
    label: 'Search Lease',
    source: 'parcel_number,location_address,notes,tenant',
    alwaysOn: true,
    fullWidth: true,
    resettable: true,
  },
  {
    type: 'ReferenceInput',
    label: 'Property Type',
    source: 'property_type_id',
    reference: 'property_types',
    allowEmpty: false,
    fullWidth: true,
    perPage: 2,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Type',
    source: 'commercial_property_type_id',
    reference: 'commercial_property_type',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Subtype',
    source: 'commercial_property_subtype_id',
    reference: 'commercial_property_subtype',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ subtype: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'subtype',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Ownership Type',
    source: 'residential_ownership_type_id',
    reference: 'residential_ownership_types',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Style',
    source: 'residential_style_id',
    reference: 'residential_styles',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ style: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'style',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Tenant',
    source: 'tenant_id',
    reference: 'contacts',
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'full_name', order: 'ASC' },
    filter: { type: 'Tenant' },
    filterToQuery: (searchText: string) => ({ full_name: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'full_name',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Lease Type',
    source: 'residential_lease_type_id',
    reference: 'residential_lease_types',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Lease Type',
    source: 'commercial_lease_type_id',
    reference: 'commercial_lease_types',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'RangeInput',
    label: 'Monthly Rent',
    source: 'residential_monthly_rent',
    fullWidth: true,
    defaultMin: 0,
    defaultMax: 1000000,
  },
  {
    type: 'DateRangeInput',
    source: 'lease_date_start',
    label: 'Lease Start Date',
    fullWidth: true,
    variant: 'standard',
  },
  {
    type: 'DateRangeInput',
    source: 'lease_date_end',
    label: 'Lease End Date',
    fullWidth: true,
    variant: 'standard',
  },
  {
    type: 'RangeInput',
    label: 'Occupancy Rate',
    source: 'commercial_occupancy_rate',
    fullWidth: true,
    defaultMin: 0,
    defaultMax: 10,
    formatter: (value: number) => value.toFixed(2),
  },
];

export const exportFields = [
  'id',
  // 'property_id',
  'parcel_number',
  'location_address',
  'property_type',
  'commercial_property_type',
  'commercial_property_subtype',
  'residential_ownership_type',
  'residential_style',
  'transaction_type',
  'commercial_lease_type',
  'residential_lease_type',
  // 'tenant_id',
  'tenant',
  'lease_date_start',
  'lease_date_end',
  'residential_monthly_rent',
  'commercial_occupancy_rate',
  'commercial_cap_rate',
  'instrument',
  'deed_book',
  'verification_sources',
  'concessions',
  'condition',
  'quality_of_construction',
  'url',
  'notes',
  'created_at',
  'updated_at',
];
