import { Field } from 'shared/components/Resource/List';

export const filterFields: Field[] = [
  {
    type: 'SearchInput',
    label: 'Search Sales',
    source: 'parcel_number,location_address,notes,grantor,grantee',
    alwaysOn: true,
    fullWidth: true,
    resettable: true,
  },
  {
    type: 'ReferenceInput',
    label: 'Grantor',
    source: 'grantor_id',
    reference: 'contacts',
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'full_name', order: 'ASC' },
    filter: { type: 'Seller' },
    filterToQuery: (searchText: string) => ({ full_name: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'full_name',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Grantee',
    source: 'grantee_id',
    reference: 'contacts',
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'full_name', order: 'ASC' },
    filter: { type: 'Buyer' },
    filterToQuery: (searchText: string) => ({ full_name: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'full_name',
      },
    ],
  },
  {
    type: 'DateRangeInput',
    source: 'sale_date',
    label: 'Sale Date',
    fullWidth: true,
    variant: 'standard',
  },
  {
    type: 'RangeInput',
    label: 'Sale Price',
    source: 'sale_price',
    fullWidth: true,
    defaultMin: 0,
    defaultMax: 1000000,
  },
  {
    type: 'ReferenceInput',
    label: 'Property Type',
    source: 'property_type_id',
    reference: 'property_types',
    allowEmpty: false,
    fullWidth: true,
    perPage: 2,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Type',
    source: 'commercial_property_type_id',
    reference: 'commercial_property_type',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Commercial Property Subtype',
    source: 'commercial_property_subtype_id',
    reference: 'commercial_property_subtype',
    alwaysOn: true,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ subtype: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'subtype',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Ownership Type',
    source: 'residential_ownership_type_id',
    reference: 'residential_ownership_types',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ type: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'type',
      },
    ],
  },
  {
    type: 'ReferenceInput',
    label: 'Residential Style',
    source: 'residential_style_id',
    reference: 'residential_styles',
    alwaysOn: true,
    allowEmpty: false,
    fullWidth: true,
    perPage: 100,
    sort: { field: 'order', order: 'ASC' },
    filterToQuery: (searchText: string) => ({ style: searchText }),
    children: [
      {
        type: 'AutocompleteInput',
        optionText: 'style',
      },
    ],
  },
  {
    type: 'RangeInput',
    label: 'Occupancy Rate',
    source: 'commercial_occupancy_rate',
    fullWidth: true,
    defaultMin: 0,
    defaultMax: 10,
    formatter: (value: number) => value.toFixed(2),
  },
  {
    type: 'RangeInput',
    label: 'Cap Rate',
    source: 'commercial_cap_rate',
    fullWidth: true,
    defaultMin: 0,
    defaultMax: 10,
    formatter: (value: number) => value.toFixed(2),
  },
];

export const exportFields = [
  'id',
  // 'property_id',
  'parcel_number',
  'location_address',
  'property_type',
  'commercial_property_type',
  'commercial_property_subtype',
  'residential_ownership_type',
  'residential_style',
  'transaction_type',
  // 'grantor_id',
  'grantor',
  // 'grantee_id',
  'grantee',
  'sale_date',
  'sale_price',
  'residential_monthly_rent',
  'commercial_occupancy_rate',
  'commercial_cap_rate',
  'instrument',
  'deed_book',
  'verification_sources',
  'concessions',
  'condition',
  'quality_of_construction',
  'url',
  'notes',
  'created_at',
  'updated_at',
];
